### ISSUE TITLE
контакты

### ISSUE THREAD

**Issue by vaskodeg** [almikh/progressive-cut#1]
а можно с вами как-то связаться по поводу кода? (через емэйл например?)

**Comment by almikh** [comment]
Ну, это сообщение мне на почту и пришло, по-правде говоря =)

вс, 27 янв. 2019 г., 21:43 vaskodeg notifications@github.com:

**Comment by almikh** [comment]
> а можно с вами как-то связаться по поводу кода? (через емэйл например?)

alexey.a.mikh@gmail.com
